package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.CustomerOrder;
import com.itheima.qiyeshixun.po.CustomerOrderExample;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.*;

public interface CustomerOrderMapper {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table customer_order
         */
        long countByExample(CustomerOrderExample example);

        int deleteByExample(CustomerOrderExample example);

        int deleteByPrimaryKey(Long id);

        int insert(CustomerOrder row);

        int insertSelective(CustomerOrder row);

        List<CustomerOrder> selectByExample(CustomerOrderExample example);

        CustomerOrder selectByPrimaryKey(Long id);

        int updateByExampleSelective(@Param("row") CustomerOrder row, @Param("example") CustomerOrderExample example);

        int updateByExample(@Param("row") CustomerOrder row, @Param("example") CustomerOrderExample example);

        int updateByPrimaryKeySelective(CustomerOrder row);

        int updateByPrimaryKey(CustomerOrder row);

        // ================== 下面是我们自定义的业务 SQL (已彻底修复状态码) ==================

        // 0. 客户下单：前端传入时默认设置为了 0 (代表：初始待审核)
        @Insert("INSERT INTO customer_order " +
                        "(customer_id, operator_id, order_no, order_status, order_type, total_amount, require_date, receive_address, order_time, create_time, update_time, del_flag) "
                        +
                        "VALUES " +
                        "(#{customerId}, #{operatorId}, #{orderNo}, #{orderStatus}, #{orderType}, #{totalAmount}, #{requireDate}, #{receiveAddress}, NOW(), NOW(), NOW(), 0)")
        @Options(useGeneratedKeys = true, keyProperty = "id")
        int insertOrder(CustomerOrder customerOrder);

        // 1. 客服工作台：查询所有待审核的订单 (order_status = 0)
        @Select("SELECT * FROM customer_order WHERE order_status = 0 AND del_flag = 0 ORDER BY create_time DESC")
        List<CustomerOrder> selectPendingOrders();

        // 2. 客服审核通过：【修正为 2】(数据库字典 2 = 可分配)。客服放行后，订单变成可分配状态。
        @Update("UPDATE customer_order SET order_status = 2, operator_id = #{operatorId}, total_amount = #{totalAmount}, update_time = NOW() WHERE id = #{id}")
        int approveOrder(@Param("id") Long id, @Param("operatorId") Long operatorId,
                        @Param("totalAmount") BigDecimal totalAmount);

        // 3. 调度中心工作台：查询可分配的订单 (也就是客服刚才改成 2 的单子)
        @Select("SELECT * FROM customer_order WHERE order_status = 2 AND del_flag = 0")
        List<CustomerOrder> selectAssignableOrders();

        // 4. 调度中心执行裂变后：【修正为 9】(这是我们自定义的扩展状态 9 = 已调度待出库)。
        // 为什么要改成 9？因为如果不改，状态还是 2，调度员刷新页面还会看到它，就会重复调度！
        @Update("UPDATE customer_order SET order_status = 9, update_time = NOW() WHERE id = #{id}")
        int updateStatusToDispatched(@Param("id") Long id);

        // 5. 分站站长派件给小哥：【修正为 5】(数据库字典 5 = 任务已分配)。
        // 代表网点站长已经把包裹指派给具体的快递员了！
        @Update("UPDATE customer_order SET order_status = 5, update_time = NOW() WHERE id = #{id}")
        int updateStatusToDelivering(@Param("id") Long id);

        // 库房出库完成，将主订单状态改为 3 (中心库已出库)
        @Update("UPDATE customer_order SET order_status = 3, update_time = NOW() WHERE id = #{id}")
        int updateStatusToOutbound(@Param("id") Long id);

        // ================= 分站库房管理员专属 SQL =================

        // 1. 查询路上跑的、待分站接收的货 (状态 3)
        @Select("SELECT * FROM customer_order WHERE order_status = 3 AND del_flag = 0")
        List<CustomerOrder> selectIncomingToStation();

        // 2. 分站库房验货入库，状态变 4 (分站已到货)
        @Update("UPDATE customer_order SET order_status = 4, update_time = NOW() WHERE id = #{id}")
        int updateStatusToStationArrived(@Param("id") Long id);

        // 3. 查询站长已经派单，正等着小哥来领的货 (状态 5)
        @Select("SELECT * FROM customer_order WHERE order_status = 5 AND del_flag = 0")
        List<CustomerOrder> selectPendingHandoverToCourier();

        // 4. 分站库房把货交给小哥，状态变 6 (已领货)
        @Update("UPDATE customer_order SET order_status = 6, update_time = NOW() WHERE id = #{id}")
        int updateStatusToCourierPicked(@Param("id") Long id);

        // 站长结单，主订单彻底完结，状态变 7 (已完成)！
        @Update("UPDATE customer_order SET order_status = 7, update_time = NOW() WHERE id = #{id}")
        int updateStatusToFinished(@Param("id") Long id);

        // ============ 订单管理模块专用 SQL ============

        // 严格级联查询历史订单 (解决前端商品名称张冠李戴问题)
        @Select("SELECT co.order_no as orderNo, co.create_time as createTime, co.order_status as orderStatus, " +
                "co.total_amount as totalAmount, oi.quantity as quantity, oi.unit_price as unitPrice, " +
                "oi.amount as itemAmount, p.product_name as productName " +
                "FROM customer_order co " +
                "LEFT JOIN order_item oi ON co.id = oi.order_id " +
                "LEFT JOIN product p ON oi.product_id = p.id " +
                "WHERE co.customer_id = #{customerId} AND co.del_flag = 0 " +
                "ORDER BY co.create_time DESC")
        List<com.itheima.qiyeshixun.dto.CustomerOrderDetailDTO> selectHistoryOrders(@Param("customerId") Long customerId);

        // 按客户ID查询其所有有效订单（含基础信息，用于退订/换货/退货选单）
        @Select("SELECT co.*, c.customer_name, c.mobile FROM customer_order co " +
                        "LEFT JOIN customer c ON co.customer_id = c.id " +
                        "WHERE co.customer_id = #{customerId} AND co.del_flag = 0 " +
                        "ORDER BY co.create_time DESC")
        List<java.util.Map<String, Object>> selectOrdersByCustomerId(@Param("customerId") Long customerId);

        // 按订单号精确查询（带客户姓名）
        @Select("SELECT co.*, c.customer_name, c.mobile FROM customer_order co " +
                        "LEFT JOIN customer c ON co.customer_id = c.id " +
                        "WHERE co.order_no = #{orderNo} AND co.del_flag = 0")
        java.util.Map<String, Object> selectOrderByOrderNo(@Param("orderNo") String orderNo);

        // 退订：软删除订单（将 del_flag=1，order_status=8 表示取消）
        @Update("UPDATE customer_order SET order_status = 8, del_flag = 1, cancel_reason = #{cancelReason}, update_time = NOW() WHERE id = #{id}")
        int cancelOrder(@Param("id") Long id, @Param("cancelReason") String cancelReason);

        // 查询指定订单的商品明细（用于换货/退货时选择商品）
        @Select("SELECT oi.*, p.product_name, p.price FROM order_item oi " +
                        "LEFT JOIN product p ON oi.product_id = p.id " +
                        "WHERE oi.order_id = #{orderId} AND oi.del_flag = 0")
        List<java.util.Map<String, Object>> selectOrderItems(@Param("orderId") Long orderId);

        // ===== 调度中心专用查询 =====

        // 查询所有【可分配】订单，联表拿客户姓名+手机
        @Select("SELECT co.*, c.customer_name, c.mobile " +
                        "FROM customer_order co " +
                        "LEFT JOIN customer c ON co.customer_id = c.id " +
                        "WHERE co.order_status = 2 AND co.del_flag = 0 " +
                        "ORDER BY co.create_time DESC")
        List<java.util.Map<String, Object>> selectAssignableOrdersWithCustomer();

        // 查询【可分配 且 dispatch_admin_id 不为 null】的订单（用于自动调度）
        @Select("SELECT co.*, c.customer_name, c.mobile " +
                        "FROM customer_order co " +
                        "LEFT JOIN customer c ON co.customer_id = c.id " +
                        "WHERE co.order_status = 2 AND co.dispatch_admin_id IS NOT NULL AND co.del_flag = 0 " +
                        "ORDER BY co.create_time DESC")
        List<java.util.Map<String, Object>> selectAutoDispatchableOrders();

        // 查询所有【缺货】订单，联表拿客户信息
        @Select("SELECT co.*, c.customer_name, c.mobile " +
                        "FROM customer_order co " +
                        "LEFT JOIN customer c ON co.customer_id = c.id " +
                        "WHERE co.order_status = 1 AND co.del_flag = 0 " +
                        "ORDER BY co.create_time DESC")
        List<java.util.Map<String, Object>> selectOutOfStockOrdersWithCustomer();
}