package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.Customer;
import com.itheima.qiyeshixun.po.CustomerExample;
import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int insert(Customer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int insertSelective(Customer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    Customer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Customer row, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Customer row, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Customer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Customer row);

    // 查出所有未被逻辑删除的客户
    @Select("SELECT * FROM customer WHERE del_flag = 0")
    List<Customer> selectAllCustomers();
    // 根据手机号查询未被删除的客户
    @Select("SELECT * FROM customer WHERE mobile = #{mobile} AND del_flag = 0 LIMIT 1")
    Customer selectByMobile(String mobile);
    // 将客户数据插入数据库
    @Insert("INSERT INTO customer(customer_name, mobile, id_card, password, address, del_flag, create_time, update_time) " +
            "VALUES(#{customerName}, #{mobile}, #{idCard}, #{password}, #{address}, 0, NOW(), NOW())")
    int insertCustomer(Customer customer);
}