package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.Inventory;
import com.itheima.qiyeshixun.po.InventoryExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface InventoryMapper {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        long countByExample(InventoryExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        int deleteByExample(InventoryExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        int deleteByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        int insert(Inventory row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        int insertSelective(Inventory row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        List<Inventory> selectByExample(InventoryExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        Inventory selectByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        int updateByExampleSelective(@Param("row") Inventory row, @Param("example") InventoryExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        int updateByExample(@Param("row") Inventory row, @Param("example") InventoryExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        int updateByPrimaryKeySelective(Inventory row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table inventory
         *
         * @mbg.generated
         */
        int updateByPrimaryKey(Inventory row);

        // 联表查询库存，并智能计算是否处于“预警状态” (补上了 p.id as productId)
        @Select("SELECT i.id as inventoryId, p.id as productId, p.product_name as productName, p.price as unitPrice, " +
                        "i.stock_quantity as stockQuantity, i.warning_level as warningLevel, " +
                        "(CASE WHEN i.stock_quantity <= i.warning_level THEN 1 ELSE 0 END) as isWarning " +
                        "FROM inventory i " +
                        "LEFT JOIN product p ON i.product_id = p.id " +
                        "WHERE i.del_flag = 0 " +
                        "ORDER BY isWarning DESC, i.stock_quantity ASC")
        List<Map<String, Object>> selectInventoryWithWarning();

        // 查询某商品在所有仓库的库存总量
        @Select("SELECT COALESCE(SUM(stock_quantity), 0) FROM inventory WHERE product_id = #{productId} AND del_flag = 0")
        int selectTotalStockByProductId(@Param("productId") Long productId);

        // 查询指定仓库的特定商品库存量
        @Select("SELECT COALESCE(SUM(stock_quantity), 0) FROM inventory WHERE product_id = #{productId} AND warehouse_id = #{warehouseId} AND del_flag = 0")
        int selectStockByProductIdAndWarehouseId(@Param("productId") Long productId, @Param("warehouseId") Long warehouseId);

        // 从有库存的仓库扣减指定数量（优先从库存最多的仓库扣）
        @Update("UPDATE inventory SET stock_quantity = stock_quantity - #{quantity}, update_time = NOW() " +
                        "WHERE product_id = #{productId} AND del_flag = 0 AND stock_quantity >= #{quantity} LIMIT 1")
        int deductStockByProductId(@Param("productId") Long productId, @Param("quantity") Integer quantity);

        // 中心库出库扣减
        @Update("UPDATE inventory SET stock_quantity = stock_quantity - #{quantity}, update_time = NOW() " +
                        "WHERE product_id = #{productId} AND warehouse_id = 1 AND del_flag = 0 AND stock_quantity >= #{quantity}")
        int deductCenterWarehouseStock(@Param("productId") Long productId, @Param("quantity") Integer quantity);

        // 获取某个商品所在的中心库房ID（用于流水表记录和加库存定位）
        @Select("SELECT id FROM inventory WHERE product_id = #{productId} AND warehouse_id = 1 AND del_flag = 0 LIMIT 1")
        Long selectCenterInventoryId(@Param("productId") Long productId);

        // 增加指定仓库的库存（如果没有则通过逻辑补救或直接加）
        @Update("UPDATE inventory SET stock_quantity = stock_quantity + #{quantity}, update_time = NOW() " +
                        "WHERE product_id = #{productId} AND warehouse_id = #{warehouseId} AND del_flag = 0")
        int addStock(@Param("productId") Long productId, @Param("warehouseId") Long warehouseId,
                        @Param("quantity") Integer quantity);

        // 以防初始没有该商品的库存记录，提供插入方法
        @Insert("INSERT INTO inventory(product_id, warehouse_id, stock_quantity, warning_level, del_flag) " +
                        "VALUES(#{productId}, #{warehouseId}, #{quantity}, 50, 0)")
        int insertStock(@Param("productId") Long productId, @Param("warehouseId") Long warehouseId,
                        @Param("quantity") Integer quantity);

        // 分站独立扣减库存（附带并发库存足够才扣减的乐观锁保障）
    @Update("UPDATE inventory SET stock_quantity = stock_quantity - #{quantity}, update_time = NOW() " +
                    "WHERE product_id = #{productId} AND warehouse_id = #{warehouseId} AND del_flag = 0 AND stock_quantity >= #{quantity}")
    int deductStationWarehouseStock(@Param("productId") Long productId, @Param("warehouseId") Long warehouseId, @Param("quantity") Integer quantity);

    // 【新增】更新储备预警值与上限
    @Update("UPDATE inventory SET warning_level = #{warningLevel}, max_level = #{maxLevel}, update_time = NOW() WHERE id = #{id}")
    int updateReservation(@Param("id") Long id, @Param("warningLevel") Integer warningLevel, @Param("maxLevel") Integer maxLevel);

    // 【新增】查询中心库房的所有库存项（带商品名称）
    @Select("SELECT i.id, i.product_id as productId, i.warehouse_id as warehouseId, " +
            "i.stock_quantity as stockQuantity, i.warning_level as warningLevel, " +
            "i.max_level as maxLevel, p.product_name as productName " +
            "FROM inventory i " +
            "LEFT JOIN product p ON i.product_id = p.id " +
            "WHERE i.warehouse_id = 1 AND i.del_flag = 0")
    List<Map<String, Object>> selectCenterInventory();

    // 【报表】综合库存查询
    @Select("<script>" +
            "SELECT i.id as inventoryId, w.warehouse_name as warehouseName, p.product_name as productName, " +
            "c.name as categoryName, p.stock_unit as stockUnit, i.stock_quantity as stockQuantity, i.warning_level as warningLevel " +
            "FROM inventory i " +
            "LEFT JOIN warehouse w ON i.warehouse_id = w.id " +
            "LEFT JOIN product p ON i.product_id = p.id " +
            "LEFT JOIN category c ON p.category_id = c.id " +
            "WHERE i.del_flag = 0 " +
            "<if test='warehouseId != null'> AND i.warehouse_id = #{warehouseId} </if> " +
            "<if test='categoryId != null'> AND p.category_id = #{categoryId} </if> " +
            "<if test='productName != null and productName != \"\"'> AND p.product_name LIKE CONCAT('%', #{productName}, '%') </if> " +
            "ORDER BY w.id ASC, p.id ASC" +
            "</script>")
    List<Map<String, Object>> selectInventoryReport(@Param("warehouseId") Long warehouseId, @Param("categoryId") Long categoryId, @Param("productName") String productName);
}