package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.OrderItem;
import com.itheima.qiyeshixun.po.OrderItemExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface OrderItemMapper {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        long countByExample(OrderItemExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        int deleteByExample(OrderItemExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        int deleteByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        int insert(OrderItem row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        int insertSelective(OrderItem row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        List<OrderItem> selectByExample(OrderItemExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        OrderItem selectByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        int updateByExampleSelective(@Param("row") OrderItem row, @Param("example") OrderItemExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        int updateByExample(@Param("row") OrderItem row, @Param("example") OrderItemExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        int updateByPrimaryKeySelective(OrderItem row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_item
         *
         * @mbg.generated
         */
        int updateByPrimaryKey(OrderItem row);

        // 插入订单明细（含单价和小计金额）
        @Insert("INSERT INTO order_item(order_id, product_id, quantity, unit_price, amount, create_time, update_time, del_flag) "
                        +
                        "VALUES(#{orderId}, #{productId}, #{quantity}, #{unitPrice}, #{amount}, NOW(), NOW(), 0)")
        int insertOrderItemFull(@Param("orderId") Long orderId, @Param("productId") Long productId,
                        @Param("quantity") Integer quantity, @Param("unitPrice") BigDecimal unitPrice,
                        @Param("amount") BigDecimal amount);

        // 保留旧方法兼容性
        @Insert("INSERT INTO order_item(order_id, product_id, quantity, create_time, update_time, del_flag) " +
                        "VALUES(#{orderId}, #{productId}, #{quantity}, NOW(), NOW(), 0)")
        int insertOrderItem(@Param("orderId") Long orderId, @Param("productId") Long productId,
                        @Param("quantity") Integer quantity);

        // 查询某订单的全部明细（含商品名称，用于缺货校验）
        @Select("SELECT oi.*, p.product_name FROM order_item oi " +
                        "LEFT JOIN product p ON oi.product_id = p.id " +
                        "WHERE oi.order_id = #{orderId} AND oi.del_flag = 0")
        List<java.util.Map<String, Object>> selectItemsByOrderId(@Param("orderId") Long orderId);
}