package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.dto.PurchaseOrderEntity;
import com.itheima.qiyeshixun.po.PurchaseOrder;
import com.itheima.qiyeshixun.po.PurchaseOrderExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PurchaseOrderMapper {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        long countByExample(PurchaseOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        int deleteByExample(PurchaseOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        int deleteByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        int insert(PurchaseOrder row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        int insertSelective(PurchaseOrder row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        List<PurchaseOrder> selectByExample(PurchaseOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        PurchaseOrder selectByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        int updateByExampleSelective(@Param("row") PurchaseOrder row, @Param("example") PurchaseOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        int updateByExample(@Param("row") PurchaseOrder row, @Param("example") PurchaseOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        int updateByPrimaryKeySelective(PurchaseOrder row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table purchase_order
         *
         * @mbg.generated
         */
        int updateByPrimaryKey(PurchaseOrder row);

        // 1. 根据商品ID查询它所属的供应商ID (从 product 表查)
        @Select("SELECT supplier_id FROM product WHERE id = #{productId}")
        Long getSupplierIdByProduct(Long productId);

        // 2. 插入采购单主表 (使用你提供的字段名)
        @Insert("INSERT INTO purchase_order (purchase_no, supplier_id, delivery_admin_id, purchase_date, total_amount, status) "
                        +
                        "VALUES (#{purchaseNo}, #{supplierId}, #{deliveryAdminId}, NOW(), #{totalAmount}, 1)")
        @Options(useGeneratedKeys = true, keyProperty = "id")
        int insertPurchaseOrder(PurchaseOrderEntity order);

        // 【新增】：向采购明细表插入数据，记录到底买了啥
        @Insert("INSERT INTO purchase_item (purchase_id, product_id, purchase_quantity, actual_quantity, unit_price, amount) "
                        +
                        "VALUES (#{purchaseId}, #{productId}, #{quantity}, 0, #{unitPrice}, #{amount})")
        int insertPurchaseItem(@org.apache.ibatis.annotations.Param("purchaseId") Long purchaseId,
                        @org.apache.ibatis.annotations.Param("productId") Long productId,
                        @org.apache.ibatis.annotations.Param("quantity") Integer quantity,
                        @org.apache.ibatis.annotations.Param("unitPrice") Double unitPrice,
                        @org.apache.ibatis.annotations.Param("amount") Double amount);

        // ===== 中心库房模块新增 =====

        // 1. 查询所有待入库(status=1)或已入库(status=2)的采购单
        @Select("<script>" +
                        "SELECT p.id, p.purchase_no, p.supplier_id, p.purchase_date, p.total_amount, p.status, p.finish_time, s.supplier_name "
                        +
                        "FROM purchase_order p " +
                        "LEFT JOIN supplier s ON p.supplier_id = s.id " +
                        "WHERE p.del_flag = 0 " +
                        "<if test='status != null'>AND p.status = #{status}</if>" +
                        "ORDER BY p.purchase_date DESC</script>")
        List<Map<String, Object>> selectPurchaseOrders(@Param("status") Byte status);

        // 2. 根据采购单查详情清单（商品信息）
        @Select("SELECT pi.id, pi.product_id, pi.purchase_quantity, pi.actual_quantity, pi.unit_price, pi.amount, pr.product_name "
                        +
                        "FROM purchase_item pi " +
                        "LEFT JOIN product pr ON pi.product_id = pr.id " +
                        "WHERE pi.purchase_id = #{purchaseId}")
        List<Map<String, Object>> selectPurchaseItems(@Param("purchaseId") Long purchaseId);

        // 3. 入库确认：更新明细表中实际到货数量
        @Update("UPDATE purchase_item SET actual_quantity = #{actualQty} WHERE id = #{itemId}")
        int updatePurchaseItemActualQty(@Param("itemId") Long itemId, @Param("actualQty") Integer actualQty);

        // 4. 入库确认：更新主表状态为已入库(3)并记录完成时间
        // 状态机：1=待发货 -> 2=在途运输中(供应商发货) -> 3=已入库(中心库房收货)
        @Update("UPDATE purchase_order SET status = 3, finish_time = NOW() WHERE id = #{purchaseId}")
        int completePurchaseOrder(@Param("purchaseId") Long purchaseId);
}
