package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.PurchaseOrder;
import com.itheima.qiyeshixun.po.PurchaseOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurchaseOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    long countByExample(PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    int deleteByExample(PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    int insert(PurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    int insertSelective(PurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    List<PurchaseOrder> selectByExample(PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    PurchaseOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PurchaseOrder row, @Param("example") PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PurchaseOrder row, @Param("example") PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PurchaseOrder row);
}