package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.PurchaseItem;
import com.itheima.qiyeshixun.po.PurchaseItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurchaseItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    long countByExample(PurchaseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int deleteByExample(PurchaseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int insert(PurchaseItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int insertSelective(PurchaseItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    List<PurchaseItem> selectByExample(PurchaseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    PurchaseItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PurchaseItem row, @Param("example") PurchaseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PurchaseItem row, @Param("example") PurchaseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PurchaseItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PurchaseItem row);
}