package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.TaskOrder;
import com.itheima.qiyeshixun.po.TaskOrderExample;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TaskOrderMapper {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        long countByExample(TaskOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        int deleteByExample(TaskOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        int deleteByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        int insert(TaskOrder row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        int insertSelective(TaskOrder row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        List<TaskOrder> selectByExample(TaskOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        TaskOrder selectByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        int updateByExampleSelective(@Param("row") TaskOrder row, @Param("example") TaskOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        int updateByExample(@Param("row") TaskOrder row, @Param("example") TaskOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        int updateByPrimaryKeySelective(TaskOrder row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table task_order
         *
         * @mbg.generated
         */
        int updateByPrimaryKey(TaskOrder row);

        // 插入任务单 (初始状态 0-待分配配送员，类型 1-正向配送)
        @Insert("INSERT INTO task_order(task_no, order_id, station_id, task_status, task_type, settlement_amount, create_time, update_time, del_flag) "
                        +
                        "VALUES(#{taskNo}, #{orderId}, #{stationId}, 0, 1, #{settlementAmount}, NOW(), NOW(), 0)")
        int insertTaskOrder(@Param("taskNo") String taskNo,
                        @Param("orderId") Long orderId,
                        @Param("stationId") Long stationId,
                        @Param("settlementAmount") BigDecimal settlementAmount);

        // 1. 查询待分配小哥的任务单 (要求必须是分站已到货状态: c.order_status = 4)
        @Select("SELECT t.id, t.task_no as taskNo, t.order_id as orderId, c.order_no as customerOrderNo, c.receive_address as receiveAddress, t.create_time as createTime "
                        +
                        "FROM task_order t " +
                        "LEFT JOIN customer_order c ON t.order_id = c.id " +
                        // 【核心修复】：增加 c.order_status = 4 的限制
                        "WHERE t.task_status = 0 AND c.order_status = 4 AND t.del_flag = 0 " +
                        "ORDER BY t.create_time ASC")
        List<Map<String, Object>> selectPendingTasks();

        // 2. 站长分配小哥 (状态改为 1-派送中，记录小哥ID和站长ID)
        @Update("UPDATE task_order SET task_status = 1, courier_id = #{courierId}, station_admin_id = #{adminId}, assign_time = NOW(), update_time = NOW() WHERE id = #{id}")
        int assignCourier(@Param("id") Long id, @Param("courierId") Long courierId, @Param("adminId") Long adminId);

        // ================= 配送员(快递小哥)专属 SQL =================

        // 1. 查询小哥自己名下【正在派送中 (task_status = 1)】的任务
        // 连表 customer_order，把收货地址和要收的钱款查出来！
        @Select("SELECT t.id as taskId, t.task_no as taskNo, c.order_no as customerOrderNo, c.receive_address as receiveAddress, c.total_amount as totalAmount, t.create_time as assignTime "
                        +
                        "FROM task_order t " +
                        "LEFT JOIN customer_order c ON t.order_id = c.id " +
                        "WHERE t.courier_id = #{courierId} AND t.task_status = 1 AND t.del_flag = 0 " +
                        "ORDER BY t.assign_time DESC")
        List<Map<String, Object>> selectMyDeliveringTasks(@Param("courierId") Long courierId);

        // 2. 小哥确认送达，将任务单状态改为 2 (已送达/待站长结单)，并记录完成时间
        @Update("UPDATE task_order SET task_status = 2, finish_time = NOW(), update_time = NOW() WHERE id = #{taskId}")
        int completeDeliveryTask(@Param("taskId") Long taskId);

        // 站长派单：绑定真实的快递小哥ID，并将任务状态改为 1 (派送中)
        @Update("UPDATE task_order SET courier_id = #{courierId}, task_status = 1, update_time = NOW() WHERE id = #{taskId}")
        int assignTaskToCourier(@Param("taskId") Long taskId, @Param("courierId") Long courierId);

        // 查询小哥送完回来的、等待站长结单的任务 (task_status = 2)
        @Select("SELECT t.id as taskId, t.order_id as orderId, t.task_no as taskNo, c.order_no as customerOrderNo, c.total_amount as totalAmount, u.real_name as courierName "
                        +
                        "FROM task_order t " +
                        "LEFT JOIN customer_order c ON t.order_id = c.id " +
                        "LEFT JOIN system_user u ON t.courier_id = u.id " +
                        "WHERE t.task_status = 2 AND t.del_flag = 0")
        List<Map<String, Object>> selectPendingCloseTasks();

        // 站长结单后，把任务单彻底完结 (设为 3)
        @Update("UPDATE task_order SET task_status = 3, update_time = NOW() WHERE id = #{taskId}")
        int closeTaskStatus(@Param("taskId") Long taskId);

        // ============ 调度中心专用 SQL ============

        // 综合查询任务单（联表 customer_order + customer）
        @Select("<script>" +
                        "SELECT t.id, t.task_no, t.station_id, t.task_status, t.task_type, t.settlement_amount, t.create_time, "
                        +
                        "co.order_no, co.receive_address, co.require_date, co.total_amount, " +
                        "c.customer_name, c.mobile " +
                        "FROM task_order t " +
                        "LEFT JOIN customer_order co ON t.order_id = co.id " +
                        "LEFT JOIN customer c ON co.customer_id = c.id " +
                        "WHERE t.del_flag = 0 " +
                        "<if test='taskNo != null and taskNo != \"\"'>AND t.task_no LIKE CONCAT('%', #{taskNo}, '%') </if>"
                        +
                        "<if test='taskStatus != null'>AND t.task_status = #{taskStatus} </if>" +
                        "<if test='stationId != null'>AND t.station_id = #{stationId} </if>" +
                        "<if test='customerName != null and customerName != \"\"'>AND c.customer_name LIKE CONCAT('%', #{customerName}, '%') </if>"
                        +
                        "<if test='mobile != null and mobile != \"\"'>AND c.mobile LIKE CONCAT('%', #{mobile}, '%') </if>"
                        +
                        "<if test='requireDateStart != null and requireDateStart != \"\"'>AND co.require_date &gt;= #{requireDateStart} </if>"
                        +
                        "<if test='requireDateEnd != null and requireDateEnd != \"\"'>AND co.require_date &lt;= #{requireDateEnd} </if>"
                        +
                        "ORDER BY t.create_time DESC" +
                        "</script>")
        List<Map<String, Object>> searchTaskOrders(
                        @Param("taskNo") String taskNo,
                        @Param("taskStatus") Byte taskStatus,
                        @Param("stationId") Long stationId,
                        @Param("customerName") String customerName,
                        @Param("mobile") String mobile,
                        @Param("requireDateStart") String requireDateStart,
                        @Param("requireDateEnd") String requireDateEnd);

        // ============ 分站管理员专用 SQL ============

        // 查询本分站的【未分配(status=0)】任务单，联表取客户信息
        @Select("<script>" +
                        "SELECT t.id, t.task_no, t.task_type, t.task_status, t.create_time, t.station_id, " +
                        "co.id as order_id, co.order_no, co.receive_address, co.total_amount, co.require_date, " +
                        "c.customer_name, c.mobile " +
                        "FROM task_order t " +
                        "LEFT JOIN customer_order co ON t.order_id = co.id " +
                        "LEFT JOIN customer c ON co.customer_id = c.id " +
                        "WHERE t.station_id = #{stationId} AND t.task_status = 0 AND t.del_flag = 0 " +
                        "<if test='taskType != null'>AND t.task_type = #{taskType} </if>" +
                        "<if test='dateStart != null and dateStart != \"\"'>AND DATE(t.create_time) &gt;= #{dateStart} </if>"
                        +
                        "<if test='dateEnd != null and dateEnd != \"\"'>AND DATE(t.create_time) &lt;= #{dateEnd} </if>"
                        +
                        "ORDER BY t.create_time ASC" +
                        "</script>")
        List<Map<String, Object>> selectStationPendingTasks(
                        @Param("stationId") Long stationId,
                        @Param("taskType") Byte taskType,
                        @Param("dateStart") String dateStart,
                        @Param("dateEnd") String dateEnd);

        // 查询本分站的【已分配(status=1)】任务单（供打印签收单和回执录入使用）
        @Select("SELECT t.id, t.task_no, t.task_type, t.task_status, t.settlement_amount, t.create_time, " +
                        "co.id as order_id, co.order_no, co.receive_address, co.total_amount, co.require_date, " +
                        "c.customer_name, c.mobile, c.address, " +
                        "u.real_name as courier_name " +
                        "FROM task_order t " +
                        "LEFT JOIN customer_order co ON t.order_id = co.id " +
                        "LEFT JOIN customer c ON co.customer_id = c.id " +
                        "LEFT JOIN system_user u ON t.courier_id = u.id " +
                        "WHERE t.station_id = #{stationId} AND t.task_status = 1 AND t.del_flag = 0 " +
                        "ORDER BY t.create_time DESC")
        List<Map<String, Object>> selectStationAssignedTasks(@Param("stationId") Long stationId);

        // 按任务单 ID 查询打印数据（含商品明细，用于打印签收单）
        @Select("SELECT t.id, t.task_no, t.task_type, t.settlement_amount, t.create_time, " +
                        "co.order_no, co.receive_address, co.total_amount, co.require_date, " +
                        "c.customer_name, c.mobile, c.id_card, " +
                        "u.real_name as courier_name " +
                        "FROM task_order t " +
                        "LEFT JOIN customer_order co ON t.order_id = co.id " +
                        "LEFT JOIN customer c ON co.customer_id = c.id " +
                        "LEFT JOIN system_user u ON t.courier_id = u.id " +
                        "WHERE t.id = #{taskId}")
        Map<String, Object> selectTaskPrintData(@Param("taskId") Long taskId);

        // 查询该任务关联订单的所有商品明细（打印用）
        @Select("SELECT oi.quantity, oi.unit_price, oi.amount, p.product_name " +
                        "FROM task_order t " +
                        "LEFT JOIN order_item oi ON t.order_id = oi.order_id " +
                        "LEFT JOIN product p ON oi.product_id = p.id " +
                        "WHERE t.id = #{taskId} AND oi.del_flag = 0")
        List<Map<String, Object>> selectTaskItems(@Param("taskId") Long taskId);

        // 回执录入：更新任务单状态、实收金额、备注、完成时间
        @Update("UPDATE task_order SET task_status = #{taskStatus}, settlement_amount = #{actualAmount}, " +
                        "remark = #{remark}, finish_time = NOW(), update_time = NOW() WHERE id = #{taskId}")
        int updateTaskReceipt(@Param("taskId") Long taskId,
                        @Param("taskStatus") Byte taskStatus,
                        @Param("actualAmount") java.math.BigDecimal actualAmount,
                        @Param("remark") String remark);

        // 缴款统计聚合查询（按分站+日期段，GROUP BY 日期）
        @Select("<script>" +
                        "SELECT DATE(t.finish_time) as settle_date, " +
                        "COUNT(CASE WHEN t.task_status IN (3,4) THEN 1 END) as delivered_count, " +
                        "COALESCE(SUM(CASE WHEN t.task_status IN (3,4) THEN t.settlement_amount ELSE 0 END), 0) as total_received, "
                        +
                        "COUNT(CASE WHEN t.task_status = 5 THEN 1 END) as failed_count, " +
                        "COALESCE(SUM(CASE WHEN t.task_status = 5 THEN t.settlement_amount ELSE 0 END), 0) as total_refund "
                        +
                        "FROM task_order t " +
                        "WHERE t.station_id = #{stationId} AND t.finish_time IS NOT NULL AND t.del_flag = 0 " +
                        "<if test='dateStart != null and dateStart != \"\"'>AND DATE(t.finish_time) &gt;= #{dateStart} </if>"
                        +
                        "<if test='dateEnd != null and dateEnd != \"\"'>AND DATE(t.finish_time) &lt;= #{dateEnd} </if>"
                        +
                        "GROUP BY DATE(t.finish_time) " +
                        "ORDER BY settle_date DESC" +
                        "</script>")
        List<Map<String, Object>> selectPaymentStats(
                        @Param("stationId") Long stationId,
                        @Param("dateStart") String dateStart,
                        @Param("dateEnd") String dateEnd);

        // ============ 分站库房管理员专用 SQL ============
        
        // 查询【待领货】的任务单
        @Select("<script>" +
                        "SELECT t.id as taskId, t.task_no as taskNo, t.station_id as stationId, t.courier_id as courierId, u.real_name as courierName, " +
                        "co.id as orderId, co.order_no as customerOrderNo, " +
                        "oi.product_id as productId, p.product_name as productName, oi.quantity " +
                        "FROM task_order t " +
                        "JOIN customer_order co ON t.order_id = co.id " +
                        "JOIN system_user u ON t.courier_id = u.id " +
                        "JOIN order_item oi ON co.id = oi.order_id " +
                        "JOIN product p ON oi.product_id = p.id " +
                        "WHERE co.order_status = 4 AND t.task_status = 1 AND t.del_flag = 0 " +
                        "<if test='stationId != null'>AND t.station_id = #{stationId}</if> " +
                        "<if test='taskNo != null and taskNo != \"\"'>AND t.task_no LIKE CONCAT('%', #{taskNo}, '%') </if>" +
                        "ORDER BY t.create_time DESC " +
                        "</script>")
        List<Map<String, Object>> selectTasksForPickup(@Param("stationId") Long stationId, @Param("taskNo") String taskNo);

        // 获取任务单关联的主订单 ID
        @Select("SELECT order_id FROM task_order WHERE id = #{taskId}")
        Long getOrderIdByTaskId(@Param("taskId") Long taskId);

        // 获取任务单包含的所有商品及数量，用于领货时扣减分站库存
        @Select("SELECT oi.product_id as productId, p.product_name as productName, oi.quantity " +
                "FROM task_order t " +
                "JOIN order_item oi ON t.order_id = oi.order_id " +
                "JOIN product p ON oi.product_id = p.id " +
                "WHERE t.id = #{taskId} AND oi.del_flag = 0")
        List<Map<String, Object>> selectTaskProductItems(@Param("taskId") Long taskId);
}