package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.TaskOrder;
import com.itheima.qiyeshixun.po.TaskOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    long countByExample(TaskOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    int deleteByExample(TaskOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    int insert(TaskOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    int insertSelective(TaskOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    List<TaskOrder> selectByExample(TaskOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    TaskOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TaskOrder row, @Param("example") TaskOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TaskOrder row, @Param("example") TaskOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskOrder row);
}