package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.TransferOrder;
import com.itheima.qiyeshixun.po.TransferOrderExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TransferOrderMapper {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        long countByExample(TransferOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        int deleteByExample(TransferOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        int deleteByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        int insert(TransferOrder row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        int insertSelective(TransferOrder row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        List<TransferOrder> selectByExample(TransferOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        TransferOrder selectByPrimaryKey(Long id);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        int updateByExampleSelective(@Param("row") TransferOrder row, @Param("example") TransferOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        int updateByExample(@Param("row") TransferOrder row, @Param("example") TransferOrderExample example);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        int updateByPrimaryKeySelective(TransferOrder row);

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table transfer_order
         *
         * @mbg.generated
         */
        int updateByPrimaryKey(TransferOrder row);

        // 插入调拨单 (初始状态 0-待中心库房出库)
        @Insert("INSERT INTO transfer_order(transfer_no, order_id, out_warehouse_id, in_warehouse_id, transfer_status, create_time, update_time, del_flag) "
                        +
                        "VALUES(#{transferNo}, #{orderId}, #{outWarehouseId}, #{inWarehouseId}, 0, NOW(), NOW(), 0)")
        int insertTransferOrder(@Param("transferNo") String transferNo,
                        @Param("orderId") Long orderId,
                        @Param("outWarehouseId") Long outWarehouseId,
                        @Param("inWarehouseId") Long inWarehouseId);

        // 1. 查询待出库的调拨单 (联合 customer_order 表，把客户单号和地址也查出来，方便库房核对)
        @Select("SELECT t.id, t.transfer_no as transferNo, t.order_id as orderId, c.order_no as customerOrderNo, c.receive_address as receiveAddress, t.create_time as createTime "
                        +
                        "FROM transfer_order t " +
                        "LEFT JOIN customer_order c ON t.order_id = c.id " +
                        "WHERE t.transfer_status = 0 AND t.del_flag = 0 " +
                        "ORDER BY t.create_time ASC")
        List<Map<String, Object>> selectPendingOutbound();

        // 2. 核心操作：确认出库 (状态改为 1，记录出库人和时间)
        @Update("UPDATE transfer_order SET transfer_status = 1, out_wh_admin_id = #{adminId}, out_time = NOW(), update_time = NOW() WHERE id = #{id}")
        int confirmOutbound(@Param("id") Long id, @Param("adminId") Long adminId);

        // 根据调拨单ID，查出它绑定的客户订单ID
        @Select("SELECT order_id FROM transfer_order WHERE id = #{id}")
        Long getOrderIdById(@Param("id") Long id);

        // ===== 中心库房模块新增 =====

        // 条件查询待出库调拨单，按日期、订单或调拨单号过滤
        @Select("<script>" +
                        "SELECT t.id, t.transfer_no as transferNo, t.order_id as orderId, t.create_time as createTime, "
                        +
                        "c.order_no as customerOrderNo, c.receive_address as receiveAddress, " +
                        "u.username as stationName, u.id as stationId " +
                        "FROM transfer_order t " +
                        "LEFT JOIN customer_order c ON t.order_id = c.id " +
                        "LEFT JOIN task_order task ON task.order_id = c.id " +
                        "LEFT JOIN system_user u ON task.station_id = u.id " +
                        "WHERE t.transfer_status = 0 AND t.del_flag = 0 " +
                        "<if test='transferNo != null and transferNo != \"\"'>AND t.transfer_no LIKE CONCAT('%', #{transferNo}, '%')</if>"
                        +
                        "<if test='orderNo != null and orderNo != \"\"'>AND c.order_no LIKE CONCAT('%', #{orderNo}, '%')</if>"
                        +
                        "<if test='dateStart != null and dateStart != \"\"'>AND DATE(t.create_time) &gt;= #{dateStart}</if>"
                        +
                        "<if test='dateEnd != null and dateEnd != \"\"'>AND DATE(t.create_time) &lt;= #{dateEnd}</if>" +
                        "ORDER BY t.create_time ASC</script>")
        List<Map<String, Object>> searchPendingTransfers(
                        @Param("transferNo") String transferNo,
                        @Param("orderNo") String orderNo,
                        @Param("dateStart") String dateStart,
                        @Param("dateEnd") String dateEnd);

        // 查调拨单里的商品详情（用于出库扣减和展示）
        @Select("SELECT oi.product_id as product_id, p.product_name as product_name, oi.quantity as quantity " +
                        "FROM transfer_order t " +
                        "JOIN customer_order co ON t.order_id = co.id " +
                        "JOIN order_item oi ON co.id = oi.order_id " +
                        "JOIN product p ON oi.product_id = p.id " +
                        "WHERE t.id = #{transferId} AND oi.del_flag = 0")
        List<Map<String, Object>> selectTransferItems(@Param("transferId") Long transferId);

        // 查询【验货单】数据统计 (查询发往某分站商品的汇总)
        @Select("<script>" +
                        "SELECT u.username as stationName, p.product_name, SUM(oi.quantity) as totalQty " +
                        "FROM transfer_order t " +
                        "JOIN customer_order c ON t.order_id = c.id " +
                        "JOIN task_order task ON task.order_id = c.id " +
                        "JOIN system_user u ON task.station_id = u.id " +
                        "JOIN order_item oi ON c.id = oi.order_id " +
                        "JOIN product p ON oi.product_id = p.id " +
                        "WHERE t.transfer_status = 1 AND t.del_flag = 0 " +
                        "<if test='stationId != null'>AND u.id = #{stationId}</if>" +
                        "<if test='dateVal != null and dateVal != \"\"'>AND DATE(t.out_time) = #{dateVal}</if>" +
                        "<if test='productName != null and productName != \"\"'>AND p.product_name LIKE CONCAT('%', #{productName}, '%')</if>"
                        +
                        "GROUP BY u.username, p.product_name " +
                        "ORDER BY u.username, p.product_name</script>")
        List<Map<String, Object>> selectInspectionPrintData(
                        @Param("stationId") Long stationId,
                        @Param("dateVal") String dateVal,
                        @Param("productName") String productName);

        // 取全站发货的分站下拉列表
        @Select("SELECT id, username as stationName FROM system_user WHERE role = 5 AND del_flag = 0")
        List<Map<String, Object>> selectAllStations();

        // 出库单统计查询 (聚合当天出库大盘)
        @Select("<script>" +
                        "SELECT DATE(t.out_time) as outDate, p.product_name, SUM(oi.quantity) as totalQty " +
                        "FROM transfer_order t " +
                        "JOIN order_item oi ON t.order_id = oi.order_id " +
                        "JOIN product p ON oi.product_id = p.id " +
                        "WHERE t.transfer_status = 1 AND t.del_flag = 0 " +
                        "<if test='dateVal != null and dateVal != \"\"'>AND DATE(t.out_time) = #{dateVal}</if>" +
                        "<if test='productName != null and productName != \"\"'>AND p.product_name LIKE CONCAT('%', #{productName}, '%')</if>"
                        +
                        "GROUP BY DATE(t.out_time), p.product_name " +
                        "ORDER BY outDate DESC, p.product_name</script>")
        List<Map<String, Object>> selectOutboundPrintData(
                        @Param("dateVal") String dateVal,
                        @Param("productName") String productName);
}