package com.itheima.qiyeshixun.mapper;

import com.itheima.qiyeshixun.po.TransferOrder;
import com.itheima.qiyeshixun.po.TransferOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransferOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    long countByExample(TransferOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    int deleteByExample(TransferOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    int insert(TransferOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    int insertSelective(TransferOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    List<TransferOrder> selectByExample(TransferOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    TransferOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TransferOrder row, @Param("example") TransferOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TransferOrder row, @Param("example") TransferOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TransferOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TransferOrder row);
}