# ===============================
# 1. ???????
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/qiyeshixun_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456

# ===============================
# 2. MyBatis ????
# ===============================
# ?? MyBatis ????????? XML SQL ??
mybatis.mapper-locations=classpath:mapper/*.xml
# ?? MyBatis ???????????? XML ???????????
mybatis.type-aliases-package=com.itheima.qiyeshixun.po
# ????????? MyBatis ????????????? SQL ??
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# ?????????????????????
mybatis.configuration.map-underscore-to-camel-case=true

# ===============================
# 3. Web ?????
# ===============================
# ???????????Vue ????????????
server.port=8080