package com.itheima.qiyeshixun.po;

import java.util.Date;

/**
 * Database Table Remarks:
 *   库存明细表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table inventory
 */
public class Inventory {
    /**
     * Database Column Remarks:
     *   库存ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   仓库ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.warehouse_id
     *
     * @mbg.generated
     */
    private Long warehouseId;

    /**
     * Database Column Remarks:
     *   商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     * Database Column Remarks:
     *   当前库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.stock_quantity
     *
     * @mbg.generated
     */
    private Integer stockQuantity;

    /**
     * Database Column Remarks:
     *   库存预警值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.warning_level
     *
     * @mbg.generated
     */
    private Integer warningLevel;

    /**
     * Database Column Remarks:
     *   最高库存值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.max_level
     *
     * @mbg.generated
     */
    private Integer maxLevel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   库存更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   逻辑删除（0=正常，1=删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.del_flag
     *
     * @mbg.generated
     */
    private Byte delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.id
     *
     * @return the value of inventory.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.id
     *
     * @param id the value for inventory.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.warehouse_id
     *
     * @return the value of inventory.warehouse_id
     *
     * @mbg.generated
     */
    public Long getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.warehouse_id
     *
     * @param warehouseId the value for inventory.warehouse_id
     *
     * @mbg.generated
     */
    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.product_id
     *
     * @return the value of inventory.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.product_id
     *
     * @param productId the value for inventory.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.stock_quantity
     *
     * @return the value of inventory.stock_quantity
     *
     * @mbg.generated
     */
    public Integer getStockQuantity() {
        return stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.stock_quantity
     *
     * @param stockQuantity the value for inventory.stock_quantity
     *
     * @mbg.generated
     */
    public void setStockQuantity(Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.warning_level
     *
     * @return the value of inventory.warning_level
     *
     * @mbg.generated
     */
    public Integer getWarningLevel() {
        return warningLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.warning_level
     *
     * @param warningLevel the value for inventory.warning_level
     *
     * @mbg.generated
     */
    public void setWarningLevel(Integer warningLevel) {
        this.warningLevel = warningLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.max_level
     *
     * @return the value of inventory.max_level
     *
     * @mbg.generated
     */
    public Integer getMaxLevel() {
        return maxLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.max_level
     *
     * @param maxLevel the value for inventory.max_level
     *
     * @mbg.generated
     */
    public void setMaxLevel(Integer maxLevel) {
        this.maxLevel = maxLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.create_time
     *
     * @return the value of inventory.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.create_time
     *
     * @param createTime the value for inventory.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.update_time
     *
     * @return the value of inventory.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.update_time
     *
     * @param updateTime the value for inventory.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.del_flag
     *
     * @return the value of inventory.del_flag
     *
     * @mbg.generated
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.del_flag
     *
     * @param delFlag the value for inventory.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Inventory other = (Inventory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWarehouseId() == null ? other.getWarehouseId() == null : this.getWarehouseId().equals(other.getWarehouseId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getStockQuantity() == null ? other.getStockQuantity() == null : this.getStockQuantity().equals(other.getStockQuantity()))
            && (this.getWarningLevel() == null ? other.getWarningLevel() == null : this.getWarningLevel().equals(other.getWarningLevel()))
            && (this.getMaxLevel() == null ? other.getMaxLevel() == null : this.getMaxLevel().equals(other.getMaxLevel()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWarehouseId() == null) ? 0 : getWarehouseId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getStockQuantity() == null) ? 0 : getStockQuantity().hashCode());
        result = prime * result + ((getWarningLevel() == null) ? 0 : getWarningLevel().hashCode());
        result = prime * result + ((getMaxLevel() == null) ? 0 : getMaxLevel().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", warehouseId=").append(warehouseId);
        sb.append(", productId=").append(productId);
        sb.append(", stockQuantity=").append(stockQuantity);
        sb.append(", warningLevel=").append(warningLevel);
        sb.append(", maxLevel=").append(maxLevel);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}