package com.itheima.qiyeshixun.po;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   发票记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table invoice
 */
public class Invoice {
    /**
     * Database Column Remarks:
     *   发票ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   发票号码（必填）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_no
     *
     * @mbg.generated
     */
    private String invoiceNo;

    /**
     * Database Column Remarks:
     *   发票金额（必填）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   登记日期（系统自动生成）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.register_date
     *
     * @mbg.generated
     */
    private Date registerDate;

    /**
     * Database Column Remarks:
     *   分站领用日期（系统自动生成）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.station_draw_date
     *
     * @mbg.generated
     */
    private Date stationDrawDate;

    /**
     * Database Column Remarks:
     *   客户领用日期（系统自动生成）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.customer_draw_date
     *
     * @mbg.generated
     */
    private Date customerDrawDate;

    /**
     * Database Column Remarks:
     *   丢失/作废日期（系统自动生成）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.lost_date
     *
     * @mbg.generated
     */
    private Date lostDate;

    /**
     * Database Column Remarks:
     *   领用分站ID（关联WAREHOUSE）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.station_id
     *
     * @mbg.generated
     */
    private Long stationId;

    /**
     * Database Column Remarks:
     *   任务单号ID（关联TASK_ORDER）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.task_id
     *
     * @mbg.generated
     */
    private Long taskId;

    /**
     * Database Column Remarks:
     *   丢失人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.lost_person
     *
     * @mbg.generated
     */
    private String lostPerson;

    /**
     * Database Column Remarks:
     *   发票状态（1=正常，2=分站已领用，3=客户已领用，4=已作废）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   财务中心管理员ID（关联SYSTEM_USER，role=7）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.finance_admin_id
     *
     * @mbg.generated
     */
    private Long financeAdminId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   逻辑删除（0=正常，1=删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.del_flag
     *
     * @mbg.generated
     */
    private Byte delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.id
     *
     * @return the value of invoice.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.id
     *
     * @param id the value for invoice.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_no
     *
     * @return the value of invoice.invoice_no
     *
     * @mbg.generated
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_no
     *
     * @param invoiceNo the value for invoice.invoice_no
     *
     * @mbg.generated
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.amount
     *
     * @return the value of invoice.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.amount
     *
     * @param amount the value for invoice.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.register_date
     *
     * @return the value of invoice.register_date
     *
     * @mbg.generated
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.register_date
     *
     * @param registerDate the value for invoice.register_date
     *
     * @mbg.generated
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.station_draw_date
     *
     * @return the value of invoice.station_draw_date
     *
     * @mbg.generated
     */
    public Date getStationDrawDate() {
        return stationDrawDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.station_draw_date
     *
     * @param stationDrawDate the value for invoice.station_draw_date
     *
     * @mbg.generated
     */
    public void setStationDrawDate(Date stationDrawDate) {
        this.stationDrawDate = stationDrawDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.customer_draw_date
     *
     * @return the value of invoice.customer_draw_date
     *
     * @mbg.generated
     */
    public Date getCustomerDrawDate() {
        return customerDrawDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.customer_draw_date
     *
     * @param customerDrawDate the value for invoice.customer_draw_date
     *
     * @mbg.generated
     */
    public void setCustomerDrawDate(Date customerDrawDate) {
        this.customerDrawDate = customerDrawDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.lost_date
     *
     * @return the value of invoice.lost_date
     *
     * @mbg.generated
     */
    public Date getLostDate() {
        return lostDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.lost_date
     *
     * @param lostDate the value for invoice.lost_date
     *
     * @mbg.generated
     */
    public void setLostDate(Date lostDate) {
        this.lostDate = lostDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.station_id
     *
     * @return the value of invoice.station_id
     *
     * @mbg.generated
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.station_id
     *
     * @param stationId the value for invoice.station_id
     *
     * @mbg.generated
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.task_id
     *
     * @return the value of invoice.task_id
     *
     * @mbg.generated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.task_id
     *
     * @param taskId the value for invoice.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.lost_person
     *
     * @return the value of invoice.lost_person
     *
     * @mbg.generated
     */
    public String getLostPerson() {
        return lostPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.lost_person
     *
     * @param lostPerson the value for invoice.lost_person
     *
     * @mbg.generated
     */
    public void setLostPerson(String lostPerson) {
        this.lostPerson = lostPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.status
     *
     * @return the value of invoice.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.status
     *
     * @param status the value for invoice.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.finance_admin_id
     *
     * @return the value of invoice.finance_admin_id
     *
     * @mbg.generated
     */
    public Long getFinanceAdminId() {
        return financeAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.finance_admin_id
     *
     * @param financeAdminId the value for invoice.finance_admin_id
     *
     * @mbg.generated
     */
    public void setFinanceAdminId(Long financeAdminId) {
        this.financeAdminId = financeAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.create_time
     *
     * @return the value of invoice.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.create_time
     *
     * @param createTime the value for invoice.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.update_time
     *
     * @return the value of invoice.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.update_time
     *
     * @param updateTime the value for invoice.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.del_flag
     *
     * @return the value of invoice.del_flag
     *
     * @mbg.generated
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.del_flag
     *
     * @param delFlag the value for invoice.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Invoice other = (Invoice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getInvoiceNo() == null ? other.getInvoiceNo() == null : this.getInvoiceNo().equals(other.getInvoiceNo()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getRegisterDate() == null ? other.getRegisterDate() == null : this.getRegisterDate().equals(other.getRegisterDate()))
            && (this.getStationDrawDate() == null ? other.getStationDrawDate() == null : this.getStationDrawDate().equals(other.getStationDrawDate()))
            && (this.getCustomerDrawDate() == null ? other.getCustomerDrawDate() == null : this.getCustomerDrawDate().equals(other.getCustomerDrawDate()))
            && (this.getLostDate() == null ? other.getLostDate() == null : this.getLostDate().equals(other.getLostDate()))
            && (this.getStationId() == null ? other.getStationId() == null : this.getStationId().equals(other.getStationId()))
            && (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getLostPerson() == null ? other.getLostPerson() == null : this.getLostPerson().equals(other.getLostPerson()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getFinanceAdminId() == null ? other.getFinanceAdminId() == null : this.getFinanceAdminId().equals(other.getFinanceAdminId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getInvoiceNo() == null) ? 0 : getInvoiceNo().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getRegisterDate() == null) ? 0 : getRegisterDate().hashCode());
        result = prime * result + ((getStationDrawDate() == null) ? 0 : getStationDrawDate().hashCode());
        result = prime * result + ((getCustomerDrawDate() == null) ? 0 : getCustomerDrawDate().hashCode());
        result = prime * result + ((getLostDate() == null) ? 0 : getLostDate().hashCode());
        result = prime * result + ((getStationId() == null) ? 0 : getStationId().hashCode());
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getLostPerson() == null) ? 0 : getLostPerson().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getFinanceAdminId() == null) ? 0 : getFinanceAdminId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", invoiceNo=").append(invoiceNo);
        sb.append(", amount=").append(amount);
        sb.append(", registerDate=").append(registerDate);
        sb.append(", stationDrawDate=").append(stationDrawDate);
        sb.append(", customerDrawDate=").append(customerDrawDate);
        sb.append(", lostDate=").append(lostDate);
        sb.append(", stationId=").append(stationId);
        sb.append(", taskId=").append(taskId);
        sb.append(", lostPerson=").append(lostPerson);
        sb.append(", status=").append(status);
        sb.append(", financeAdminId=").append(financeAdminId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}