package com.itheima.qiyeshixun.po;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   配送任务单表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table task_order
 */
public class TaskOrder {
    /**
     * Database Column Remarks:
     *   任务单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   任务单号（唯一）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.task_no
     *
     * @mbg.generated
     */
    private String taskNo;

    /**
     * Database Column Remarks:
     *   关联客户订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     * Database Column Remarks:
     *   所属分站ID（关联WAREHOUSE）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.station_id
     *
     * @mbg.generated
     */
    private Long stationId;

    /**
     * Database Column Remarks:
     *   配送员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.courier_id
     *
     * @mbg.generated
     */
    private Long courierId;

    /**
     * Database Column Remarks:
     *   分站管理员ID（关联SYSTEM_USER，role=3）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.station_admin_id
     *
     * @mbg.generated
     */
    private Long stationAdminId;

    /**
     * Database Column Remarks:
     *   任务状态（1=未分配，2=已分配，3=配送中，4=已完成，5=部分完成，6=失败/取消）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.task_status
     *
     * @mbg.generated
     */
    private Byte taskStatus;

    /**
     * Database Column Remarks:
     *   任务类型（1=送货收款，2=送货，3=退货，4=换货）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.task_type
     *
     * @mbg.generated
     */
    private Byte taskType;

    /**
     * Database Column Remarks:
     *   需结算金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.settlement_amount
     *
     * @mbg.generated
     */
    private BigDecimal settlementAmount;

    /**
     * Database Column Remarks:
     *   分配时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.assign_time
     *
     * @mbg.generated
     */
    private Date assignTime;

    /**
     * Database Column Remarks:
     *   完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.finish_time
     *
     * @mbg.generated
     */
    private Date finishTime;

    /**
     * Database Column Remarks:
     *   配送备注/回执信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   逻辑删除（0=正常，1=删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_order.del_flag
     *
     * @mbg.generated
     */
    private Byte delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.id
     *
     * @return the value of task_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.id
     *
     * @param id the value for task_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.task_no
     *
     * @return the value of task_order.task_no
     *
     * @mbg.generated
     */
    public String getTaskNo() {
        return taskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.task_no
     *
     * @param taskNo the value for task_order.task_no
     *
     * @mbg.generated
     */
    public void setTaskNo(String taskNo) {
        this.taskNo = taskNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.order_id
     *
     * @return the value of task_order.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.order_id
     *
     * @param orderId the value for task_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.station_id
     *
     * @return the value of task_order.station_id
     *
     * @mbg.generated
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.station_id
     *
     * @param stationId the value for task_order.station_id
     *
     * @mbg.generated
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.courier_id
     *
     * @return the value of task_order.courier_id
     *
     * @mbg.generated
     */
    public Long getCourierId() {
        return courierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.courier_id
     *
     * @param courierId the value for task_order.courier_id
     *
     * @mbg.generated
     */
    public void setCourierId(Long courierId) {
        this.courierId = courierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.station_admin_id
     *
     * @return the value of task_order.station_admin_id
     *
     * @mbg.generated
     */
    public Long getStationAdminId() {
        return stationAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.station_admin_id
     *
     * @param stationAdminId the value for task_order.station_admin_id
     *
     * @mbg.generated
     */
    public void setStationAdminId(Long stationAdminId) {
        this.stationAdminId = stationAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.task_status
     *
     * @return the value of task_order.task_status
     *
     * @mbg.generated
     */
    public Byte getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.task_status
     *
     * @param taskStatus the value for task_order.task_status
     *
     * @mbg.generated
     */
    public void setTaskStatus(Byte taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.task_type
     *
     * @return the value of task_order.task_type
     *
     * @mbg.generated
     */
    public Byte getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.task_type
     *
     * @param taskType the value for task_order.task_type
     *
     * @mbg.generated
     */
    public void setTaskType(Byte taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.settlement_amount
     *
     * @return the value of task_order.settlement_amount
     *
     * @mbg.generated
     */
    public BigDecimal getSettlementAmount() {
        return settlementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.settlement_amount
     *
     * @param settlementAmount the value for task_order.settlement_amount
     *
     * @mbg.generated
     */
    public void setSettlementAmount(BigDecimal settlementAmount) {
        this.settlementAmount = settlementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.assign_time
     *
     * @return the value of task_order.assign_time
     *
     * @mbg.generated
     */
    public Date getAssignTime() {
        return assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.assign_time
     *
     * @param assignTime the value for task_order.assign_time
     *
     * @mbg.generated
     */
    public void setAssignTime(Date assignTime) {
        this.assignTime = assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.finish_time
     *
     * @return the value of task_order.finish_time
     *
     * @mbg.generated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.finish_time
     *
     * @param finishTime the value for task_order.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.remark
     *
     * @return the value of task_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.remark
     *
     * @param remark the value for task_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.create_time
     *
     * @return the value of task_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.create_time
     *
     * @param createTime the value for task_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.update_time
     *
     * @return the value of task_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.update_time
     *
     * @param updateTime the value for task_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_order.del_flag
     *
     * @return the value of task_order.del_flag
     *
     * @mbg.generated
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_order.del_flag
     *
     * @param delFlag the value for task_order.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskOrder other = (TaskOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTaskNo() == null ? other.getTaskNo() == null : this.getTaskNo().equals(other.getTaskNo()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getStationId() == null ? other.getStationId() == null : this.getStationId().equals(other.getStationId()))
            && (this.getCourierId() == null ? other.getCourierId() == null : this.getCourierId().equals(other.getCourierId()))
            && (this.getStationAdminId() == null ? other.getStationAdminId() == null : this.getStationAdminId().equals(other.getStationAdminId()))
            && (this.getTaskStatus() == null ? other.getTaskStatus() == null : this.getTaskStatus().equals(other.getTaskStatus()))
            && (this.getTaskType() == null ? other.getTaskType() == null : this.getTaskType().equals(other.getTaskType()))
            && (this.getSettlementAmount() == null ? other.getSettlementAmount() == null : this.getSettlementAmount().equals(other.getSettlementAmount()))
            && (this.getAssignTime() == null ? other.getAssignTime() == null : this.getAssignTime().equals(other.getAssignTime()))
            && (this.getFinishTime() == null ? other.getFinishTime() == null : this.getFinishTime().equals(other.getFinishTime()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTaskNo() == null) ? 0 : getTaskNo().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getStationId() == null) ? 0 : getStationId().hashCode());
        result = prime * result + ((getCourierId() == null) ? 0 : getCourierId().hashCode());
        result = prime * result + ((getStationAdminId() == null) ? 0 : getStationAdminId().hashCode());
        result = prime * result + ((getTaskStatus() == null) ? 0 : getTaskStatus().hashCode());
        result = prime * result + ((getTaskType() == null) ? 0 : getTaskType().hashCode());
        result = prime * result + ((getSettlementAmount() == null) ? 0 : getSettlementAmount().hashCode());
        result = prime * result + ((getAssignTime() == null) ? 0 : getAssignTime().hashCode());
        result = prime * result + ((getFinishTime() == null) ? 0 : getFinishTime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskNo=").append(taskNo);
        sb.append(", orderId=").append(orderId);
        sb.append(", stationId=").append(stationId);
        sb.append(", courierId=").append(courierId);
        sb.append(", stationAdminId=").append(stationAdminId);
        sb.append(", taskStatus=").append(taskStatus);
        sb.append(", taskType=").append(taskType);
        sb.append(", settlementAmount=").append(settlementAmount);
        sb.append(", assignTime=").append(assignTime);
        sb.append(", finishTime=").append(finishTime);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}