package com.itheima.qiyeshixun.po;

import java.util.Date;

/**
 * Database Table Remarks:
 *   调拨订单表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table transfer_order
 */
public class TransferOrder {
    /**
     * Database Column Remarks:
     *   调拨单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   调拨单号（唯一）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.transfer_no
     *
     * @mbg.generated
     */
    private String transferNo;

    /**
     * Database Column Remarks:
     *   关联客户订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     * Database Column Remarks:
     *   出库仓库ID（中心仓）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.out_warehouse_id
     *
     * @mbg.generated
     */
    private Long outWarehouseId;

    /**
     * Database Column Remarks:
     *   入库仓库ID（分站仓）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.in_warehouse_id
     *
     * @mbg.generated
     */
    private Long inWarehouseId;

    /**
     * Database Column Remarks:
     *   中心库房管理员ID（关联SYSTEM_USER，role=4）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.out_wh_admin_id
     *
     * @mbg.generated
     */
    private Long outWhAdminId;

    /**
     * Database Column Remarks:
     *   分站库房管理员ID（关联SYSTEM_USER，role=5）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.in_wh_admin_id
     *
     * @mbg.generated
     */
    private Long inWhAdminId;

    /**
     * Database Column Remarks:
     *   调拨状态（1=待出库，2=已出库，3=已入库，4=取消）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.transfer_status
     *
     * @mbg.generated
     */
    private Byte transferStatus;

    /**
     * Database Column Remarks:
     *   出库时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.out_time
     *
     * @mbg.generated
     */
    private Date outTime;

    /**
     * Database Column Remarks:
     *   入库时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.in_time
     *
     * @mbg.generated
     */
    private Date inTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   逻辑删除（0=正常，1=删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_order.del_flag
     *
     * @mbg.generated
     */
    private Byte delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.id
     *
     * @return the value of transfer_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.id
     *
     * @param id the value for transfer_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.transfer_no
     *
     * @return the value of transfer_order.transfer_no
     *
     * @mbg.generated
     */
    public String getTransferNo() {
        return transferNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.transfer_no
     *
     * @param transferNo the value for transfer_order.transfer_no
     *
     * @mbg.generated
     */
    public void setTransferNo(String transferNo) {
        this.transferNo = transferNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.order_id
     *
     * @return the value of transfer_order.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.order_id
     *
     * @param orderId the value for transfer_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.out_warehouse_id
     *
     * @return the value of transfer_order.out_warehouse_id
     *
     * @mbg.generated
     */
    public Long getOutWarehouseId() {
        return outWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.out_warehouse_id
     *
     * @param outWarehouseId the value for transfer_order.out_warehouse_id
     *
     * @mbg.generated
     */
    public void setOutWarehouseId(Long outWarehouseId) {
        this.outWarehouseId = outWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.in_warehouse_id
     *
     * @return the value of transfer_order.in_warehouse_id
     *
     * @mbg.generated
     */
    public Long getInWarehouseId() {
        return inWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.in_warehouse_id
     *
     * @param inWarehouseId the value for transfer_order.in_warehouse_id
     *
     * @mbg.generated
     */
    public void setInWarehouseId(Long inWarehouseId) {
        this.inWarehouseId = inWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.out_wh_admin_id
     *
     * @return the value of transfer_order.out_wh_admin_id
     *
     * @mbg.generated
     */
    public Long getOutWhAdminId() {
        return outWhAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.out_wh_admin_id
     *
     * @param outWhAdminId the value for transfer_order.out_wh_admin_id
     *
     * @mbg.generated
     */
    public void setOutWhAdminId(Long outWhAdminId) {
        this.outWhAdminId = outWhAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.in_wh_admin_id
     *
     * @return the value of transfer_order.in_wh_admin_id
     *
     * @mbg.generated
     */
    public Long getInWhAdminId() {
        return inWhAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.in_wh_admin_id
     *
     * @param inWhAdminId the value for transfer_order.in_wh_admin_id
     *
     * @mbg.generated
     */
    public void setInWhAdminId(Long inWhAdminId) {
        this.inWhAdminId = inWhAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.transfer_status
     *
     * @return the value of transfer_order.transfer_status
     *
     * @mbg.generated
     */
    public Byte getTransferStatus() {
        return transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.transfer_status
     *
     * @param transferStatus the value for transfer_order.transfer_status
     *
     * @mbg.generated
     */
    public void setTransferStatus(Byte transferStatus) {
        this.transferStatus = transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.out_time
     *
     * @return the value of transfer_order.out_time
     *
     * @mbg.generated
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.out_time
     *
     * @param outTime the value for transfer_order.out_time
     *
     * @mbg.generated
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.in_time
     *
     * @return the value of transfer_order.in_time
     *
     * @mbg.generated
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.in_time
     *
     * @param inTime the value for transfer_order.in_time
     *
     * @mbg.generated
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.create_time
     *
     * @return the value of transfer_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.create_time
     *
     * @param createTime the value for transfer_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.update_time
     *
     * @return the value of transfer_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.update_time
     *
     * @param updateTime the value for transfer_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.del_flag
     *
     * @return the value of transfer_order.del_flag
     *
     * @mbg.generated
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.del_flag
     *
     * @param delFlag the value for transfer_order.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TransferOrder other = (TransferOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTransferNo() == null ? other.getTransferNo() == null : this.getTransferNo().equals(other.getTransferNo()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getOutWarehouseId() == null ? other.getOutWarehouseId() == null : this.getOutWarehouseId().equals(other.getOutWarehouseId()))
            && (this.getInWarehouseId() == null ? other.getInWarehouseId() == null : this.getInWarehouseId().equals(other.getInWarehouseId()))
            && (this.getOutWhAdminId() == null ? other.getOutWhAdminId() == null : this.getOutWhAdminId().equals(other.getOutWhAdminId()))
            && (this.getInWhAdminId() == null ? other.getInWhAdminId() == null : this.getInWhAdminId().equals(other.getInWhAdminId()))
            && (this.getTransferStatus() == null ? other.getTransferStatus() == null : this.getTransferStatus().equals(other.getTransferStatus()))
            && (this.getOutTime() == null ? other.getOutTime() == null : this.getOutTime().equals(other.getOutTime()))
            && (this.getInTime() == null ? other.getInTime() == null : this.getInTime().equals(other.getInTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTransferNo() == null) ? 0 : getTransferNo().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOutWarehouseId() == null) ? 0 : getOutWarehouseId().hashCode());
        result = prime * result + ((getInWarehouseId() == null) ? 0 : getInWarehouseId().hashCode());
        result = prime * result + ((getOutWhAdminId() == null) ? 0 : getOutWhAdminId().hashCode());
        result = prime * result + ((getInWhAdminId() == null) ? 0 : getInWhAdminId().hashCode());
        result = prime * result + ((getTransferStatus() == null) ? 0 : getTransferStatus().hashCode());
        result = prime * result + ((getOutTime() == null) ? 0 : getOutTime().hashCode());
        result = prime * result + ((getInTime() == null) ? 0 : getInTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", transferNo=").append(transferNo);
        sb.append(", orderId=").append(orderId);
        sb.append(", outWarehouseId=").append(outWarehouseId);
        sb.append(", inWarehouseId=").append(inWarehouseId);
        sb.append(", outWhAdminId=").append(outWhAdminId);
        sb.append(", inWhAdminId=").append(inWhAdminId);
        sb.append(", transferStatus=").append(transferStatus);
        sb.append(", outTime=").append(outTime);
        sb.append(", inTime=").append(inTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}